name: Building TWRP Android 11

on: # [push]
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
  DEVICE: begonia
  DT_LINK: https://github.com/ZyCromerZ/twrp_redmi_begonia -b android-11.0
  DT_PATH: device/redmi/begonia
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TARGET: recoveryimage
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="-1001400256602" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="Initializing environment for compiling TWRP"
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove landscape-common
            git config --global user.name "ZyCromerZ"
            git config --global user.email "neetroid97@gmail.com"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean 
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync TWRP A11 source and device tree
         run: |
             curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="-1001400256602" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="Sync TWRP A11 source and device tree"
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1 --partial-clone --clone-filter=blob:limit=10M --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4
             git clone $DT_LINK --single-branch $DT_PATH
             
       - name: Building TWRP
         run: |
              curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="-1001400256602" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="Building TWRP"
              cd work
              . build/envsetup.sh && lunch twrp_$DEVICE-eng 
              repo sync -j4
              export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET -j4
             
       - name: Uploading recovery image
         run: |
              curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="-1001400256602" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="Uploading recovery image"
              cd work/out/target/product/$DEVICE
              ZipName="[$(date +"%Y%m%d")]TWRP-begonia-3.6.0_11.zip"
              sudo zip -r9 "$ZipName" recovery.img
              ls > ls.txt
              curl -F chat_id="-1001400256602" -F document=@ls.txt -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument -F caption="Check it out @clurfe"
              curl -F chat_id="-1001434683571" -F document=@$ZipName https://api.telegram.org/bot$BOT_TOKEN/sendDocument -F caption="Please test it @clurfe"
               curl -sL https://git.io/file-transfer | sh
               ./transfer wet $ZipName
               ./transfer wet recovery.img
