name: Building TWRP 

on: # [push]
#  release:
#    types: [published]
#  push:
#    branches:
#      - android-9
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: "git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0"
  DEVICE: Infinix_X573
  DT_LINK: "https://github.com/skyhuppa/Infinix_X573 -b android-9"
  DT_PATH: device/Infinix/Infinix_X573
  TARGET: recoveryimage
  WorkSpace: WorkSpace
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
         
       - name: Initializing environment
         run: |
               mkdir -p /tmp/recovery
               cd /tmp/recovery
               apt install openssh-server openjdk-8-jdk -y
               apt update --fix-missing
               apt install openssh-server openjdk-8-jdk -y
            
       - name: Sync TWRP 9 source and device tree
         run: |
             mkdir work
             cd work
             repo init --depth=1 -u $MANIFEST -g default,-device,-mips,-darwin,-notdefault 
             repo sync -j4
             git clone $DT_LINK --single-branch $DT_PATH
             
       - name: Building TWRP
         run: |
                rm -rf out
                source build/envsetup.sh
                echo " source build/envsetup.sh done"
                export ALLOW_MISSING_DEPENDENCIES=true
                export LC_ALL="C"
                lunch twrp_${DEVICE}-eng || abort " lunch failed with exit status $?"
                echo " lunch twrp_${DEVICE}-eng done"
                mka recoveryimage || abort " mka failed with exit status $?"
                echo " mka recoveryimage done"
              
       - name: Uploading recovery image
         run: |
              echo " ===+++ Uploading Recovery +++==="
              version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d \" -f2)
              OUTFILE=TWRP-${version}-${DEVICE}-$(date "+%Y%m%d-%I%M").zip

              cd out/target/product/$DEVICE
              mv recovery.img ${OUTFILE%.zip}.img
              zip -r9 $OUTFILE ${OUTFILE%.zip}.img
              curl -T $OUTFILE https://oshi.at
